// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgziakpykxcwiwrkljkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnemlha3B5a3hjd2l3cmtsamt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDA5MTEsImV4cCI6MjA2NTgxNjkxMX0.ClQKQNeot4heDbNf1d_ZBF28L9Y6N6fQ1hP1a4zftyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);